### PR TITLE
enable av_register_all(), support writing to stdout

### PR DESCRIPTION
**Pull request by ashimokawa**

### CODE REVIEW

**Comment by ashimokawa** [comment]
I forgot to create a feature branch, so this is in one PR now.

**Review by padgettr — COMMENTED** [review]
That's great, thanks

**Review by padgettr — COMMENTED** [review]
The second change for writing streams to stdout: unfortunately I don't get much time to work on this, I tend to do a bit here and there as I use it and find problems, so I have a different version which I haven't yet committed to github on my laptop. Some of the changes will conflict with those you have made: one change is I got rid of getopt() because I kept getting segfaults which I couldn't solve, so gave up on it. This means the option handling has changed somewhat! I'll try and merge writing to stdout offline and make required changes, but it could take some time as I'm very busy at the moment... thanks for taking the time to make these changes though, writing to stdout is certainly a useful feature!

**Comment by ashimokawa** [comment]
@padgettr 
You are welcome ;)

I just needed working stdout support for some experiment, and wanted to share the changes.
Not a problem if you won't merge them at all.

If you do merge them (or redo the function your way and close this PR), I will delete my fork again.

**Comment by padgettr** [comment]
I have merged the changes with my offline copy and uploaded, so should all be in sync now. All seems to be OK, but let me know if you find any problems! I have added a switch in Makefile for the av_register_all() call, as this isn't required in ffmpeg >=4.0 (I'm currently using v4.1), you can enable it by uncommenting the line in the Makefile if you're using an older version. Also tried to clean up some of the text output, some of it was really just for de-bugging and didn't give any useful info relating to the transcode!

**Pull request closed without merging**
